<a href="https://colab.research.google.com/github/Heo-DaMoon/Hello/blob/master/02_MathPrimer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

##Matrix multiplication

In [ ]:
a = np.array([[1, -3, 2], [4, 0, -5]])
print(a)

[[ 1 -3  2]
 [ 4  0 -5]]


In [ ]:
a.shape

(2, 3)

In [ ]:
b = np.array([[3], [1], [2]])
print(b)

[[3]
 [1]
 [2]]


In [ ]:
c = np.matmul(a, b)
print(c)

[[4]
 [2]]


In [ ]:
d = np.dot(a, b)
print(d)

[[4]
 [2]]


In [ ]:
d.shape

(2, 1)